cursor #ecdfe5
cursor_text_color #d2c2ca

foreground            #ecdfe5
background            #181216
selection_foreground  #3e2a38
selection_background  #dcbed1
url_color             #f5b2e2

color0  #4c4c4c
color8  #262626
color1  #ac8a8c
color9  #c49ea0
color2  #8aac8b
color10 #9ec49f
color3  #aca98a
color11 #c4c19e
color4  #f5b2e2
color12 #a39ec4
color5  #ac8aac
color13 #c49ec4
color6  #8aacab
color14 #9ec3c4
color7  #f0f0f0
color15 #e7e7e7
