cursor #e8e0e8
cursor_text_color #ccc4cf

foreground            #e8e0e8
background            #151218
selection_foreground  #362d40
selection_background  #cfc1da
url_color             #d8bafa

color0  #4c4c4c
color8  #262626
color1  #ac8a8c
color9  #c49ea0
color2  #8aac8b
color10 #9ec49f
color3  #aca98a
color11 #c4c19e
color4  #d8bafa
color12 #a39ec4
color5  #ac8aac
color13 #c49ec4
color6  #8aacab
color14 #9ec3c4
color7  #f0f0f0
color15 #e7e7e7
