cursor #e6e1e9
cursor_text_color #cac4cf

foreground            #e6e1e9
background            #141218
selection_foreground  #332d41
selection_background  #cbc3dc
url_color             #cebdfe

color0   #141218
color1   #ff7290
color2   #7ffe99
color3   #ffda72
color4   #baa7f1
color5   #4c3e76
color6   #cebdfe
color7   #f3efff
color8   #434149
color9   #ff9fb3
color10  #a5ffb8
color11  #ffe7a5
color12  #d6c7ff
color13  #ddd1ff
color14  #e9e1ff
color15  #faf8ff
