cursor #dee4de
cursor_text_color #c0c9c1

foreground            #dee4de
background            #0f1511
selection_foreground  #20352a
selection_background  #b4ccbc
url_color             #8fd5b0

color0   #0f1511
color1   #f4966e
color2   #6ad56d
color3   #fff172
color4   #7acaa0
color5   #005236
color6   #8fd5b0
color7   #d2dfdb
color8   #3c4441
color9   #ffbb9f
color10  #a5ffa8
color11  #fff6a5
color12  #a8eac7
color13  #c4ffdf
color14  #d9ffeb
color15  #f8fffc
