cursor #ece1d4
cursor_text_color #d1c5b4

foreground            #ece1d4
background            #17130b
selection_foreground  #3c2e15
selection_background  #dac4a0
url_color             #edc06c

color0   #17130b
color1   #ff7266
color2   #7fed6c
color3   #ffe566
color4   #e1ad4e
color5   #5e4200
color6   #edc06c
color7   #f8f4e8
color8   #45423c
color9   #ff9f96
color10  #acff9d
color11  #ffee9d
color12  #ffd589
color13  #ffdd9d
color14  #ffe9c0
color15  #fffcf8
