# Fuzzel - Plantilla Maestra Optimizada (Matugen)

[main]
# POSICIONAMIENTO Y APARIENCIA
anchor=top-left
x-margin=0
y-margin=0
font=Source Sans Pro:size=11, monospace:size=11
prompt="Buscar > "

# ICONOS Y APLICACIONES
icon-theme=default
icons-enabled=yes
# Aumenta el tamaño de los iconos (0.5 es el estándar, 0.7 es más grande)
image-size-ratio=0.7

# Desactivar acciones para mostrar solo aplicaciones
show-actions=no

# BÚSQUEDA (Corregido 'nane')
fields=name,generic,comment,categories,keywords
match-mode=fzf
terminal=kitty

# GEOMETRÍA
lines=15
width=35
horizontal-pad=25
vertical-pad=12
inner-pad=5

[colors]
# Fondo cristal (bf = transparencia)
background=11140ebf
text=e2e3d9ff
match=aed18dff
selection=33362ebf
selection-text=e2e3d9ff
selection-match=aed18dff
border=aed18dff

[border]
width=2
radius=5
