# Fuzzel - Plantilla Maestra Optimizada para Matugen y Niri Blur

[main]
# POSICIONAMIENTO Y APARIENCIA
anchor=top-left
x-margin=0
y-margin=0
font=Source Sans Pro:size=11, monospace:size=11
prompt="Buscar > "

# ICONOS Y APLICACIONES
icon-theme=Vivid-Dark-Icons
icons-enabled=yes
# Ratio alto para que los iconos luzcan grandes junto a la fuente 12
image-size-ratio=1.5

# Desactivar acciones para mostrar solo aplicaciones
show-actions=no

# BÚSQUEDA
fields=name,generic,comment,categories,keywords
match-mode=fzf
terminal=kitty

# GEOMETRÍA
# Ajustada con padding extra para que los iconos grandes no queden pegados a los bordes
lines=15
width=35
horizontal-pad=25
vertical-pad=15
inner-pad=8

[colors]
# Fondo cristal translúcido (90). Ideal para resaltar el efecto blur de Niri.
background=1a110f90
text=f1dfdaff
match=ffb59dff
selection=3d322fbf
selection-text=f1dfdaff
selection-match=ffb59dff
border=ffb59dff

[border]
# Grosor y suavizado de esquinas que combina con las ventanas de Niri
width=2
radius=5
